/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyCourses"];
        put?: never;
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCourseTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModules"];
        put?: never;
        post: operations["createModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/modules/{moduleId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLessons"];
        put?: never;
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/modules/{moduleId}/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Partial update - only non-null fields are applied, so completed and bookmarked can be toggled independently with the same endpoint. */
        patch: operations["updateLessonState"];
        trace?: never;
    };
    "/courses/{courseId}/modules/{moduleId}/lessons/{lessonId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Hinglish text-to-speech audio for the lesson. */
        get: operations["getLessonAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Kicks off the asynchronous AI generation pipeline for a topic. */
        post: operations["generateCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{pipelineRunId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. Most recent 50 pipeline runs across all users. */
        get: operations["listAdminJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. Most recent 50 FAILED job steps across all users. */
        get: operations["listAdminErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{pipelineRunId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Admin only. */
        post: operations["cancelAdminJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/cancel-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Admin only. Cancels every active (PENDING/RUNNING) run. */
        post: operations["cancelAllAdminJobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiKeyStatus"];
        /** @description Provider is always "gemini" server-side; not client-supplied. */
        put: operations["setApiKey"];
        post?: never;
        delete: operations["deleteApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            status?: number;
            error?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CreateCourseRequest: {
            title: string;
            description?: string | null;
            tags?: string[] | null;
        };
        CourseResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
        };
        CourseTreeResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            modules: components["schemas"]["ModuleWithLessonsResponse"][];
        };
        CourseExportResponse: {
            title: string;
            description: string | null;
            tags: string[];
            modules: components["schemas"]["CourseExportResponseModuleExport"][];
        };
        CourseExportResponseModuleExport: {
            title: string;
            orderIndex: number;
            lessons: components["schemas"]["CourseExportResponseLessonExport"][];
        };
        CourseExportResponseLessonExport: {
            title: string;
            orderIndex: number;
            objectives: string[];
            content: components["schemas"]["ContentBlock"][];
            isEnriched: boolean;
        };
        CreateModuleRequest: {
            title: string;
            orderIndex: number;
        };
        ModuleResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            orderIndex: number;
        };
        ModuleWithLessonsResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            orderIndex: number;
            lessons: components["schemas"]["LessonSummaryResponse"][];
        };
        CreateLessonRequest: {
            title: string;
            orderIndex: number;
            objectives?: string[] | null;
            content?: components["schemas"]["ContentBlock"][] | null;
        };
        LessonResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            orderIndex: number;
            objectives: string[];
            content: components["schemas"]["ContentBlock"][];
            isEnriched: boolean;
            completed: boolean;
            bookmarked: boolean;
        };
        LessonSummaryResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            orderIndex: number;
            isEnriched: boolean;
            completed: boolean;
            bookmarked: boolean;
        };
        /** @description Omit a field to leave it unchanged; include it to set that field. */
        UpdateLessonStateRequest: {
            completed?: boolean;
            bookmarked?: boolean;
        };
        GenerateCourseRequest: {
            topic: string;
        };
        GenerateCourseResponse: {
            /** Format: uuid */
            pipelineRunId: string;
        };
        JobStatusResponse: {
            /** Format: uuid */
            pipelineRunId: string;
            status: components["schemas"]["JobStatus"];
            currentStep: components["schemas"]["JobStepType"] | null;
            /** Format: int64 */
            position: number;
            /** Format: uuid */
            courseId: string | null;
            error: string | null;
            usingDefaultKey: boolean;
            keyFallbackReason: string | null;
        };
        PipelineRunSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId: string;
            status: components["schemas"]["JobStatus"];
            /** Format: uuid */
            courseId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        JobErrorSummary: {
            /** Format: uuid */
            stepId: string;
            /** Format: uuid */
            pipelineRunId: string;
            type: components["schemas"]["JobStepType"];
            error: string;
            attempt: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminStatsResponse: {
            /** Format: int64 */
            totalRuns: number;
            /** Format: int64 */
            doneRuns: number;
            /** Format: int64 */
            failedRuns: number;
        };
        SetApiKeyRequest: {
            apiKey: string;
        };
        ApiKeyStatusResponse: {
            configured: boolean;
        };
        /** @enum {string} */
        JobStatus: "PENDING" | "RUNNING" | "DONE" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        JobStepType: "OUTLINE" | "LESSON_CONTENT" | "ENRICHMENT";
        ContentBlock: components["schemas"]["HeadingBlock"] | components["schemas"]["ParagraphBlock"] | components["schemas"]["CodeBlock"] | components["schemas"]["VideoBlock"] | components["schemas"]["McqBlock"];
        HeadingBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heading";
            text: string;
        };
        ParagraphBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paragraph";
            text: string;
        };
        CodeBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
            language: string;
            text: string;
        };
        VideoBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** @description A YouTube search query string, never a direct URL. */
            query: string;
        };
        McqBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mcq";
            question: string;
            options: string[];
            /** @description 0-based index into options. */
            answer: number;
            explanation: string;
        };
    };
    responses: {
        /** @description Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Authenticated but not authorized (e.g. not an admin) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found, or not owned by the current user */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CourseId: string;
        CourseIdInPath: string;
        ModuleIdInPath: string;
        LessonIdInPath: string;
        PipelineRunIdInPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMyCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Courses owned by the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseRequest"];
            };
        };
        responses: {
            /** @description Course created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full course tree as a portable JSON export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseExportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCourseTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course with its modules and lessons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modules for the course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModuleRequest"];
            };
        };
        responses: {
            /** @description Module created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
                moduleId: components["parameters"]["ModuleIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson summaries for the module */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummaryResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
                moduleId: components["parameters"]["ModuleIdInPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLessonRequest"];
            };
        };
        responses: {
            /** @description Lesson created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
                moduleId: components["parameters"]["ModuleIdInPath"];
                lessonId: components["parameters"]["LessonIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full lesson content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLessonState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
                moduleId: components["parameters"]["ModuleIdInPath"];
                lessonId: components["parameters"]["LessonIdInPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLessonStateRequest"];
            };
        };
        responses: {
            /** @description Updated lesson */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLessonAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseIdInPath"];
                moduleId: components["parameters"]["ModuleIdInPath"];
                lessonId: components["parameters"]["LessonIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WAV audio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    generateCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCourseRequest"];
            };
        };
        responses: {
            /** @description Generation accepted, poll /jobs/{pipelineRunId}/status */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateCourseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipelineRunId: components["parameters"]["PipelineRunIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status of the generation job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent pipeline runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminErrors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent job errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobErrorSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate pipeline stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    cancelAdminJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipelineRunId: components["parameters"]["PipelineRunIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelAllAdminJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of runs cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getApiKeyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether a personal API key is configured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetApiKeyRequest"];
            };
        };
        responses: {
            /** @description Key stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
